train:
  train_runner: fse_editor
  train_dis: True
  dis_train_start_step: 45000
  steps: 500000



model:
  method: fse_full
  device: "0"
  batch_size: 8
  # workers: 2


encoder_losses:
  l2: 1.0
  lpips: 0.8
  id: 0.1
  adv: 0.01


disc_losses:
  main:
    coef: 1
  r1:
    coef: 10


optimizers:
    ranger:
      lr: 0.0001

# metrics:
#     fid:
#        batch_size: 16
#        n_workers: 2
#     lpips:
#        n_workers: 2
#     id_vit:
#        n_workers: 2
#     l2:
#        n_workers: 2

dist:
  enabled: true         # 是否启用分布式训练
  port: 12345            # 通信端口
  sync_bn: true          # 是否使用SyncBatchNorm
  find_unused_parameters: true  # 是否找到未使用的参数
  world_size: 4          # 使用的GPU数量
  rank: 0                # 初始进程排名(会被自动设置)